# Generated by Django 3.2.5 on 2021-07-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.CharField(max_length=3, verbose_name='Yaş'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Soyisim'),
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.IntegerField(verbose_name='Numara'),
        ),
        migrations.AlterField(
            model_name='student',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi'),
        ),
    ]
