# Generated by Django 3.2.5 on 2021-07-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210708_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('number',)},
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(max_length=3, verbose_name='Yaş'),
        ),
    ]
