# Generated by Django 3.2.5 on 2021-07-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210709_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('-number',)},
        ),
    ]
